-- Group exercises that are the same movement with a different setup (posture,
-- equipment, grip, one arm vs two) so they read as one entry in the catalog and
-- pickers. Each stays its own exercise, keeping its own history and defaults.
-- (variant_group / variant_label were added in 0034.)
update exercises e
set variant_group = v.grp, variant_label = v.label
from (values
  -- legs
  ('Lying Leg Curl',                        'Hamstring Curl', 'Lying'),
  ('Seated Leg Curl',                       'Hamstring Curl', 'Seated'),
  ('Single-Leg Hamstring Curl (Seated)',    'Hamstring Curl', 'Single-leg seated'),
  ('Leg Extension',                         'Leg Extension',  'Both legs'),
  ('Single-Leg Leg Extension',              'Leg Extension',  'Single leg'),
  ('Standing Calf Raise',                   'Calf Raise',     'Standing'),
  ('Seated Calf Raise',                     'Calf Raise',     'Seated'),
  ('Conventional Deadlift',                 'Deadlift',       'Conventional'),
  ('Sumo Deadlift',                         'Deadlift',       'Sumo'),
  ('Hex-Bar Deadlift',                      'Deadlift',       'Hex bar'),
  ('Romanian Deadlift',                     'Romanian Deadlift', 'Both legs'),
  ('Single-Leg Romanian Deadlift',          'Romanian Deadlift', 'Single leg'),
  ('Barbell Lunges',                        'Lunge',          'Barbell'),
  ('Walking Lunge',                         'Lunge',          'Walking'),
  ('Goblet Squat',                          'Goblet Squat',   'Standard'),
  ('Kettlebell Goblet Squat',               'Goblet Squat',   'Kettlebell'),
  -- core
  ('Cable Crunch',                          'Crunch',         'Cable'),
  ('Crunch Machine',                        'Crunch',         'Machine'),
  -- chest
  ('Barbell Bench Press',                   'Bench Press',    'Barbell'),
  ('Dumbbell Bench Press',                  'Bench Press',    'Dumbbell'),
  ('Smith Machine Bench Press',             'Bench Press',    'Smith machine'),
  ('Close-Grip Bench Press',                'Bench Press',    'Close grip'),
  ('Incline Barbell Press',                 'Incline Press',  'Barbell'),
  ('Incline Dumbbell Press',                'Incline Press',  'Dumbbell'),
  ('Incline Chest Press Machine',           'Incline Press',  'Machine'),
  ('Decline Barbell Bench Press',           'Decline Press',  'Barbell'),
  ('Decline Dumbbell Press',                'Decline Press',  'Dumbbell'),
  ('Dumbbell Flyes (Flat)',                 'Dumbbell Fly',   'Flat'),
  ('Incline Dumbbell Flyes',                'Dumbbell Fly',   'Incline'),
  ('Decline Dumbbell Flyes',                'Dumbbell Fly',   'Decline'),
  ('Cable Fly',                             'Cable Fly',      'Flat'),
  ('Decline Cable Flyes',                   'Cable Fly',      'Decline'),
  ('Cable Crossover (High to Low)',         'Cable Fly',      'Crossover, high to low'),
  ('Cable Crossover (Low to High)',         'Cable Fly',      'Crossover, low to high'),
  ('Push-Up',                               'Push-Up',        'Standard'),
  ('Incline Push-Up',                       'Push-Up',        'Incline'),
  ('Decline Push-Up',                       'Push-Up',        'Decline'),
  ('Diamond Push-Up',                       'Push-Up',        'Diamond'),
  ('Wide-Grip Push-Ups',                    'Push-Up',        'Wide grip'),
  -- back
  ('Pull-up',                               'Pull-Up',        'Overhand'),
  ('Chin-Ups',                              'Pull-Up',        'Underhand (chin-up)'),
  ('Neutral-Grip Pull-Up',                  'Pull-Up',        'Neutral grip'),
  ('Assisted Pull-up',                      'Pull-Up',        'Assisted'),
  ('Seated Cable Row',                      'Cable Row',      'Seated'),
  ('Wide-Grip Cable Row',                   'Cable Row',      'Wide grip'),
  ('Standing Underhand-Grip Cable Row',     'Cable Row',      'Standing, underhand'),
  ('Single-Arm Cable Row',                  'Cable Row',      'Single arm'),
  ('T-Bar Row',                             'T-Bar Row',      'Barbell'),
  ('T-Bar Row Machine',                     'T-Bar Row',      'Machine'),
  ('Dumbbell Pullover',                     'Pullover',       'Dumbbell'),
  ('Cable Pullover',                        'Pullover',       'Cable'),
  ('Barbell Shrug',                         'Shrug',          'Barbell'),
  ('Dumbbell Shrug',                        'Shrug',          'Dumbbell'),
  -- shoulders
  ('Barbell Shoulder Press',                'Shoulder Press', 'Barbell'),
  ('Overhead Barbell Press',                'Shoulder Press', 'Overhead barbell'),
  ('Dumbbell Shoulder Press',               'Shoulder Press', 'Dumbbell'),
  ('Shoulder Press Machine',                'Shoulder Press', 'Machine'),
  ('Arnold Press',                          'Shoulder Press', 'Arnold'),
  ('Single-Arm Supinated Dumbbell Press',   'Shoulder Press', 'Single-arm supinated'),
  ('Dumbbell Lateral Raise',                'Lateral Raise',  'Dumbbell'),
  ('Cable Lateral Raise',                   'Lateral Raise',  'Cable'),
  ('Dumbbell Front Raises',                 'Front Raise',    'Dumbbell'),
  ('Cable Front Raise',                     'Front Raise',    'Cable'),
  ('Bent-Over Rear Delt Raise',             'Rear Delt Fly',  'Bent-over'),
  ('Cable Rear Delt Flyes',                 'Rear Delt Fly',  'Cable'),
  ('Pec Deck Rear Delt Flyes',              'Rear Delt Fly',  'Pec deck'),
  ('Upright Row',                           'Upright Row',    'Standard'),
  ('Barbell Upright Row',                   'Upright Row',    'Barbell'),
  ('Dumbbell Upright Row',                  'Upright Row',    'Dumbbell'),
  -- arms
  ('Barbell Curl',                          'Biceps Curl',    'Barbell'),
  ('EZ-Bar Curl',                           'Biceps Curl',    'EZ-bar'),
  ('Dumbbell Bicep Curl',                   'Biceps Curl',    'Dumbbell'),
  ('Cable Curl',                            'Biceps Curl',    'Cable'),
  ('Preacher Curl',                         'Preacher Curl',  'Standard'),
  ('Seated Preacher Curl',                  'Preacher Curl',  'Seated'),
  ('Dumbbell Hammer Curl',                  'Hammer Curl',    'Dumbbell'),
  ('Rope Hammer Curl',                      'Hammer Curl',    'Rope'),
  ('Single-Arm Cable Hammer Curl',          'Hammer Curl',    'Single-arm cable'),
  ('Cable Triceps Pushdown',                'Triceps Pushdown', 'Standard'),
  ('Reverse-Grip Triceps Pushdown',         'Triceps Pushdown', 'Reverse grip'),
  ('Single-Arm Rope Pushdown',              'Triceps Pushdown', 'Single-arm rope'),
  ('Bent-Over Tricep Pushdown',             'Triceps Pushdown', 'Bent-over'),
  ('Overhead Triceps Extension',            'Overhead Triceps Extension', 'Standard'),
  ('Overhead Barbell Tricep Extension',     'Overhead Triceps Extension', 'Barbell'),
  ('Single-Arm Overhead Tricep Extension',  'Overhead Triceps Extension', 'Single arm'),
  ('Cable Wrist Curls',                     'Wrist Curl',     'Standard'),
  ('Cable Reverse Wrist Curl',              'Wrist Curl',     'Reverse')
) as v(name, grp, label)
where e.name = v.name and e.archived_at is null;
